import js from '@eslint/js';
import prettier from 'eslint-config-prettier/flat';
import boundaries from 'eslint-plugin-boundaries';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import unicorn from 'eslint-plugin-unicorn';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      'dist',
      'coverage',
      'node_modules',
      'playwright-report',
      'test-results',
      // Generated by `openapi-typescript` (pnpm generate:api); schema.contract.test.ts
      // guards it against drift, so lint fixes here would be reverted on the next regen.
      'src/shared/api/schema.d.ts',
      // Vite's scaffolded ambient-types file (`/// <reference types="vite/client" />`).
      'src/vite-env.d.ts',
    ],
  },
  {
    extends: [
      js.configs.recommended,
      ...tseslint.configs.strictTypeChecked,
      ...tseslint.configs.stylisticTypeChecked,
      unicorn.configs.recommended,
    ],
    files: ['**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2022,
      globals: globals.browser,
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
      boundaries,
    },
    settings: {
      'boundaries/include': ['src/**/*.{ts,tsx}', 'test/**/*.{ts,tsx}'],
      'boundaries/ignore': ['src/**/*.d.ts'],
      'boundaries/elements': [
        { type: 'app', pattern: ['src/app', 'test/app'], mode: 'folder' },
        { type: 'shared', pattern: ['src/shared', 'test/shared'], mode: 'folder' },
        {
          type: 'feature',
          pattern: ['src/features/*', 'test/features/*'],
          mode: 'folder',
          capture: ['feature'],
        },
        {
          type: 'testkit',
          pattern: ['test/support/*', 'test/*.test.{ts,tsx}'],
          mode: 'file',
        },
        { type: 'entrypoint', pattern: 'src/main.tsx', mode: 'file' },
      ],
      'import/resolver': {
        typescript: {
          project: ['./tsconfig.app.json', './tsconfig.test.json'],
          noWarnOnMultipleProjects: true,
        },
      },
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],
      'boundaries/no-unknown-dependencies': 'error',
      'boundaries/no-unknown-files': 'error',
      'boundaries/dependencies': [
        'error',
        {
          default: 'disallow',
          policies: [
            {
              from: { element: { type: 'testkit' } },
              allow: { to: { element: { types: ['app', 'shared', 'feature', 'testkit'] } } },
            },
            {
              from: { element: { type: 'entrypoint' } },
              allow: { to: { element: { types: ['app', 'shared'] } } },
            },
            {
              from: { element: { type: 'app' } },
              allow: { to: { element: { types: ['app', 'shared', 'feature', 'testkit'] } } },
            },
            {
              from: { element: { type: 'feature' } },
              allow: { to: { element: { types: ['shared', 'testkit'] } } },
            },
            {
              from: { element: { type: 'feature' } },
              allow: {
                to: {
                  element: {
                    type: 'feature',
                    captured: { feature: '{{ from.element.captured.feature }}' },
                  },
                },
              },
            },
            {
              from: { element: { type: 'shared' } },
              allow: { to: { element: { type: 'shared' } } },
            },
          ],
        },
      ],
      // Dropped from unicorn's `recommended` per ADR-0010: abbreviations read fine in this
      // codebase, `null` is deliberate at the API/JSON edge, `reduce` and nested ternaries
      // are allowed style.
      'unicorn/prevent-abbreviations': 'off',
      'unicorn/no-null': 'off',
      'unicorn/no-array-reduce': 'off',
      'no-nested-ternary': 'off',
      // Added to unicorn's `recommended` in v66-v74; dropped per ADR-0010 for the same
      // reasons as the rules above. `name-replacements` is `prevent-abbreviations` by
      // another name (`ref` -> `reference`, `searchParams` -> `searchParameters`);
      // member order, module-scoped mutable state set from a function (in-flight guards,
      // per-test fixtures), promise chaining, and the routes.tsx composition-root
      // `installApiAuth()` call are all deliberate here.
      'unicorn/name-replacements': 'off',
      'unicorn/consistent-class-member-order': 'off',
      'unicorn/no-top-level-assignment-in-function': 'off',
      'unicorn/prefer-await': 'off',
      'unicorn/no-top-level-side-effects': 'off',
      'unicorn/filename-case': ['error', { cases: { camelCase: true, pascalCase: true } }],
      // Deviations from strict/stylistic-type-checked, recorded in ADR-0010: this codebase
      // models its domain with `type` unions, not interfaces; and interpolating a numeric
      // HTTP status into an error message is idiomatic here.
      '@typescript-eslint/consistent-type-definitions': ['error', 'type'],
      '@typescript-eslint/restrict-template-expressions': ['error', { allowNumber: true }],
      // The domain switches are terse `case x: return y`; only brace cases that need it.
      'unicorn/switch-case-braces': ['error', 'avoid'],
      // React Router loaders redirect by throwing the Response from `redirect()`.
      '@typescript-eslint/only-throw-error': [
        'error',
        { allow: [{ from: 'lib', name: 'Response' }] },
      ],
    },
  },
  {
    files: ['**/*.test.{ts,tsx}', 'test/support/**'],
    languageOptions: { globals: { ...globals.browser, ...globals.node } },
  },
  {
    files: ['vite.config.ts'],
    languageOptions: { globals: globals.node },
    settings: { 'boundaries/include': [] },
  },
  {
    files: ['e2e/**/*.ts', 'visual/**/*.ts', 'playwright.config.ts', 'playwright.visual.config.ts'],
    languageOptions: { globals: globals.node },
    settings: { 'boundaries/include': [] },
  },
  prettier,
);
