#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=12

# Run from the repo root regardless of where the wizard is invoked.
REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
cd "$REPO_ROOT"

# All wizard state is local until it's shipped to the box: the box .env is built
# up here, then scp'd across in Stage 10. Both dirs are gitignored.
STATE_DIR="scripts/deploy/.state"
SSH_DIR="scripts/deploy/.ssh"
mkdir -p "$STATE_DIR" "$SSH_DIR"
chmod 700 "$SSH_DIR"
ENV_FILE="$STATE_DIR/box.env"          # every write_env below lands here
CI_KEY="$SSH_DIR/pictogram_deploy"     # the key CI uses to reach the box

# ssh/scp into the box as the `deploy` user with the CI key (no agent, no host
# prompt — the wizard has already trusted the host in Stage 5).
box_ssh()  { ssh  -i "$CI_KEY" -o StrictHostKeyChecking=accept-new "deploy@${DEPLOY_HOST}" "$@"; }
box_scp()  { scp  -i "$CI_KEY" -o StrictHostKeyChecking=accept-new "$@"; }
# Run a command on the box before the deploy user/key exist, via gcloud's own SSH
# (it manages its keys and the OS Login / metadata dance).
gvm() { gcloud compute ssh "$VM_NAME" --zone "$VM_ZONE" --command "$1"; }

banner "Pictogram deployment (ADR-0012)"
say "Provisions the temporary GCP box, wires CI to it, and prepares the box .env."
note "Pre-domain stages run now; the domain-gated tail (Stage 12) waits until you own the domain."

# ── Stage 1 ──────────────────────────────────────────────────────────────
stage "Preflight"
say "Checking the tools this wizard drives."
missing=0
for bin in gcloud gh node ssh scp openssl; do
  if command -v "$bin" >/dev/null 2>&1; then
    step "$bin ✓"
  else
    warn "$bin is not on PATH"
    missing=1
  fi
done
if [[ "$missing" == 1 ]]; then
  warn "Install the missing tools and re-run. gcloud: https://cloud.google.com/sdk/docs/install"
  exit 1
fi
if gh auth status >/dev/null 2>&1; then
  step "gh authenticated ✓"
else
  say "gh is not logged in. In another terminal run:  gh auth login  (needs the 'repo' scope)"
  pause "Press Enter once gh auth login succeeds"
fi

# ── Stage 2 ──────────────────────────────────────────────────────────────
stage "GCP: sign in and pick the project"
say "The box lives in a GCP project you own. This uses the \$300 free-trial credit"
say "as an explicitly temporary host — migrating off GCP before it expires is #176."
open_url "https://console.cloud.google.com/projectcreate"
step "Create a project (e.g. 'pictogram') or note an existing project ID."
say "Signing in to gcloud (a browser window will open):"
gcloud auth login
ask GCP_PROJECT "Project ID:"
gcloud config set project "$GCP_PROJECT"
write_env GCP_PROJECT "$GCP_PROJECT"

# ── Stage 3 ──────────────────────────────────────────────────────────────
stage "GCP: link billing and enable Compute"
say "The project needs the billing account that carries the free-trial credit."
open_url "https://console.cloud.google.com/billing"
step "Copy the Billing account ID of the account holding the credit (format 0X0X0X-0X0X0X-0X0X0X)."
ask GCP_BILLING "Billing account ID:"
gcloud billing projects link "$GCP_PROJECT" --billing-account "$GCP_BILLING"
write_env GCP_BILLING "$GCP_BILLING"
say "Enabling the Compute Engine API (takes ~1 min):"
gcloud services enable compute.googleapis.com

# ── Stage 4 ──────────────────────────────────────────────────────────────
stage "GCP: static IP and firewall"
ask VM_REGION "Region [europe-west1]:"; VM_REGION="${VM_REGION:-europe-west1}"
ask VM_ZONE   "Zone [${VM_REGION}-b]:"; VM_ZONE="${VM_ZONE:-${VM_REGION}-b}"
write_env VM_REGION "$VM_REGION"
write_env VM_ZONE "$VM_ZONE"
say "Reserving a static external IP ('pictogram-ip'):"
gcloud compute addresses create pictogram-ip --region "$VM_REGION" 2>/dev/null \
  || note "pictogram-ip already exists — reusing it"
DEPLOY_HOST=$(gcloud compute addresses describe pictogram-ip --region "$VM_REGION" --format 'value(address)')
say "Static IP: $DEPLOY_HOST"
say "Opening 22/80/443 to the box ('pictogram-ingress'):"
gcloud compute firewall-rules create pictogram-ingress \
  --allow tcp:22,tcp:80,tcp:443 --target-tags pictogram --direction INGRESS 2>/dev/null \
  || note "pictogram-ingress already exists — reusing it"

# ── Stage 5 ──────────────────────────────────────────────────────────────
stage "GCP: create the VM"
say "e2-medium (2 vCPU / 4 GB), Ubuntu LTS, 30 GB disk, tagged 'pictogram'."
note "~\$28/month all-in, covered by the credit for ~10 months."
VM_NAME="pictogram"
if gcloud compute instances describe "$VM_NAME" --zone "$VM_ZONE" >/dev/null 2>&1; then
  note "Instance 'pictogram' already exists — skipping creation."
else
  confirm "Create the e2-medium instance now?" || { warn "Aborted."; exit 1; }
  gcloud compute instances create "$VM_NAME" \
    --zone "$VM_ZONE" \
    --machine-type e2-medium \
    --image-family ubuntu-2404-lts-amd64 --image-project ubuntu-os-cloud \
    --boot-disk-size 30GB --boot-disk-type pd-balanced \
    --address pictogram-ip \
    --tags pictogram
fi
write_env DEPLOY_HOST "$DEPLOY_HOST"
say "Waiting for SSH on the box to come up..."
until gvm "true" >/dev/null 2>&1; do printf '.'; sleep 5; done
printf '\n'; step "box reachable ✓"

# ── Stage 6 ──────────────────────────────────────────────────────────────
stage "CI deploy key + the deploy user"
say "CI reaches the box over SSH as a dedicated 'deploy' user with its own key."
if [[ -f "$CI_KEY" ]]; then
  note "Key already generated at $CI_KEY — reusing it."
else
  ssh-keygen -t ed25519 -N '' -C 'pictogram-ci-deploy' -f "$CI_KEY" >/dev/null
  step "generated $CI_KEY"
fi
CI_PUBKEY=$(cat "${CI_KEY}.pub")
say "Creating the 'deploy' user on the box and trusting the key:"
gvm "sudo useradd -m -s /bin/bash deploy 2>/dev/null || true; \
     sudo mkdir -p /home/deploy/.ssh /home/deploy/pictogram; \
     echo '$CI_PUBKEY' | sudo tee /home/deploy/.ssh/authorized_keys >/dev/null; \
     sudo chmod 700 /home/deploy/.ssh; sudo chmod 600 /home/deploy/.ssh/authorized_keys; \
     sudo chown -R deploy:deploy /home/deploy/.ssh /home/deploy/pictogram"
DEPLOY_USER=deploy
write_env DEPLOY_USER "$DEPLOY_USER"
box_ssh "echo connected as \$(whoami)" && step "CI key works ✓"

# ── Stage 7 ──────────────────────────────────────────────────────────────
stage "Box: install Docker"
say "Docker Engine + the compose plugin, from Docker's official convenience script."
gvm "command -v docker >/dev/null 2>&1 && echo present || (curl -fsSL https://get.docker.com | sudo sh)"
gvm "sudo usermod -aG docker deploy"
box_ssh "docker version --format '{{.Server.Version}}'" && step "docker ready for the deploy user ✓"

# ── Stage 8 ──────────────────────────────────────────────────────────────
stage "Box: log in to GHCR"
say "The box pulls the app/chat/caddy images from GitHub Container Registry."
open_url "https://github.com/settings/tokens/new?scopes=read:packages&description=pictogram-box-ghcr"
step "Generate a classic token with only 'read:packages'. Copy it."
ask GHCR_USER "Your GitHub username:"
ask_secret GHCR_TOKEN "Paste the read:packages token:"
box_ssh "docker login ghcr.io -u '$GHCR_USER' --password-stdin" <<<"$GHCR_TOKEN" \
  && step "GHCR login stored on the box ✓"
note "Not written anywhere local — it lives only in the box's docker config."

# ── Stage 9 ──────────────────────────────────────────────────────────────
stage "Generate the box secrets"
say "Signing key (ADR-0004), its public half for chat (ADR-0014), and DB / MinIO creds."
if [[ -n "$(_existing PICTOGRAM_AUTH_SIGNING_KEY || true)" ]] && ! confirm "Signing key already generated — regenerate it?"; then
  note "Keeping the existing signing key."
else
  SIGNING_KEY=$(node -e '
    const { webcrypto } = require("crypto");
    (async () => {
      const kp = await webcrypto.subtle.generateKey({ name: "ECDSA", namedCurve: "P-256" }, true, ["sign", "verify"]);
      const jwk = await webcrypto.subtle.exportKey("jwk", kp.privateKey);
      const kid = "pictogram-" + new Date().toISOString().slice(0, 10) + "-" + Math.random().toString(36).slice(2, 8);
      process.stdout.write(JSON.stringify({ kty: jwk.kty, crv: jwk.crv, kid, x: jwk.x, y: jwk.y, d: jwk.d }));
    })();
  ')
  PUBLIC_KEY=$(node -e 'const j = JSON.parse(process.argv[1]); delete j.d; process.stdout.write(JSON.stringify(j));' "$SIGNING_KEY")
  write_env PICTOGRAM_AUTH_SIGNING_KEY "$SIGNING_KEY"
  write_env PICTOGRAM_AUTH_PUBLIC_KEY "$PUBLIC_KEY"
fi
[[ -n "$(_existing POSTGRES_PASSWORD || true)" ]] || write_env POSTGRES_PASSWORD "$(openssl rand -hex 24)"
[[ -n "$(_existing MINIO_ROOT_USER || true)"   ]] || write_env MINIO_ROOT_USER "pictogram"
[[ -n "$(_existing MINIO_ROOT_PASSWORD || true)" ]] || write_env MINIO_ROOT_PASSWORD "$(openssl rand -hex 24)"
write_env PICTOGRAM_TAG "latest"
step "box.env now holds $(grep -c '=' "$ENV_FILE") values"

# ── Stage 10 ─────────────────────────────────────────────────────────────
stage "Ship the compose files and .env to the box"
say "Copies compose.yaml, compose.prod.yaml and Caddyfile.prod into ~/pictogram,"
say "and the assembled box.env as ~/pictogram/.env."
box_scp compose.yaml compose.prod.yaml Caddyfile.prod "deploy@${DEPLOY_HOST}:pictogram/"
box_scp "$ENV_FILE" "deploy@${DEPLOY_HOST}:pictogram/.env"
box_ssh "chmod 600 pictogram/.env && ls -l pictogram/"
step "box is staged — it will start serving once Stage 12 fills the domain + OAuth values"

# ── Stage 11 ─────────────────────────────────────────────────────────────
stage "GitHub: the deploy secrets"
say "The Deploy workflow (.github/workflows/deploy.yml) reads these."
set_secret DEPLOY_SSH_KEY "$(cat "$CI_KEY")"
set_secret DEPLOY_HOST "$DEPLOY_HOST"
set_secret DEPLOY_USER "$DEPLOY_USER"
# Pin the box's host key so CI verifies it instead of trust-on-first-use. If the box is
# ever rebuilt (the #176 migration), re-run this stage to refresh it.
set_secret DEPLOY_KNOWN_HOSTS "$(ssh-keyscan "$DEPLOY_HOST" 2>/dev/null)"
note "DEPLOY_HOST is the IP for now; Stage 12 swaps it for the domain."

# ── Stage 12 ─────────────────────────────────────────────────────────────
stage "Domain-gated tail — run this part once you own the domain"
say "Everything above is done. The box is provisioned and CI can reach it, but it"
say "cannot serve until it has a domain (for the TLS cert) and a real Google OAuth"
say "client. Do the following when the domain is registered, then re-run this wizard"
say "(the earlier stages will no-op) or apply the steps by hand:"
printf '\n'
step "Register the domain (Cloudflare Registrar / Porkbun) and delegate DNS."
step "DNS: add  A  @  ${DEPLOY_HOST}   (and AAAA if the VM has IPv6). No CNAME on the apex,"
step "     and DNS-only — NOT proxied (Cloudflare's orange cloud breaks ACME + rate limits)."
open_url "https://console.cloud.google.com/apis/credentials"
step "Create an OAuth 2.0 Client ID, type 'Web application'."
step "Authorized redirect URI:  https://<domain>/login/oauth2/code/google"
step "Configure the OAuth consent screen (app name, support email, scopes openid + email)."
printf '\n'
if confirm "Have the domain and OAuth client details now?"; then
  ask PICTOGRAM_DOMAIN "Domain (e.g. pictogram.example):"
  ask GOOGLE_CLIENT_ID "Google client ID:"
  ask_secret GOOGLE_CLIENT_SECRET "Google client secret:"
  write_env PICTOGRAM_DOMAIN "$PICTOGRAM_DOMAIN"
  write_env GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
  write_env GOOGLE_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET"
  box_scp "$ENV_FILE" "deploy@${DEPLOY_HOST}:pictogram/.env"
  box_ssh "chmod 600 pictogram/.env"
  set_secret DEPLOY_HOST "$PICTOGRAM_DOMAIN"
  # Re-key the pinned host entry for the domain name (same box key, connected-as name).
  set_secret DEPLOY_KNOWN_HOSTS "$(ssh-keyscan "$DEPLOY_HOST" 2>/dev/null | sed "s/^[^ ]*/$PICTOGRAM_DOMAIN/")"
  say "Now trigger the Deploy workflow:  Actions → Deploy → Run workflow"
  say "Then work through the smoke test in docs/runbook/deployment.md."
else
  note "No problem — re-run the wizard when you're ready; Stages 1–11 will skip."
fi

finish
