#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" ["note"] shows the opening frame: what this wizard does, and
# (when running a subset of stages) which ones.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  if [[ -n "${2:-}" ]]; then
    printf '%s  %s%s\n' "$DIM" "$2" "$RESET"
  fi
  printf '\n'
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage N clears the screen, then announces stage N (its name comes from
# STAGE_TITLES, authored in the stages section) and shows progress.
stage() {
  _STAGE_INDEX="$1"
  _clear
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "${STAGE_TITLES[$1 - 1]}" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=14

# One title per stage, in order — stage() looks up its own name here, and
# it backs --list and the stage-selection usage message below.
STAGE_TITLES=(
  "Preflight"
  "GCP: sign in and pick the project"
  "GCP: link billing and enable Compute"
  "GCP: static IP and firewall"
  "GCP: create the VM"
  "CI deploy key + the deploy user"
  "Box: install Docker"
  "Box: log in to GHCR"
  "Generate the box secrets"
  "Grafana Cloud: metrics + logs credentials (ADR-0016)"
  "Ship the compose files and .env to the box"
  "GitHub: the deploy secrets"
  "Sentry: exception tracking (ADR-0016)"
  "Domain-gated tail — run this part once you own the domain"
)

# ── Stage selection ─────────────────────────────────────────────────────
# No argument: every stage runs, in order (first-time setup). A stage spec —
# a number, a range "A-B", or a comma-separated mix of either ("9,11-13") —
# runs only those, still in ascending order. A stage that reads a value an
# earlier, unselected stage would normally have computed (DEPLOY_HOST,
# VM_ZONE, GCP_PROJECT) falls back to what's already in ENV_FILE, below.
usage() {
  cat <<EOF
Usage: $(basename "$0") [STAGE_SPEC | -l | -h]

  STAGE_SPEC   run only these stages, e.g. "9", "9-12", "9,11,13"
  -l, --list   print every stage's number and name, then exit
  -h, --help   this message

With no argument, every stage runs (first-time setup).
EOF
}

SELECTED_LIST=()

# is_selected N: true if stage N is in SELECTED_LIST.
is_selected() {
  local target="$1" n
  for n in "${SELECTED_LIST[@]}"; do
    [[ "$n" == "$target" ]] && return 0
  done
  return 1
}

# parse_stage_spec "9,11-13": validates and appends each stage number in the
# spec to SELECTED_LIST.
parse_stage_spec() {
  local spec="$1" part lo hi n
  for part in ${spec//,/ }; do
    if [[ "$part" =~ ^([0-9]+)-([0-9]+)$ ]]; then
      lo="${BASH_REMATCH[1]}"; hi="${BASH_REMATCH[2]}"
    elif [[ "$part" =~ ^[0-9]+$ ]]; then
      lo="$part"; hi="$part"
    else
      printf 'error: not a stage number or range: %s\n' "$part" >&2
      exit 1
    fi
    if (( lo < 1 || hi > TOTAL_STAGES || lo > hi )); then
      printf 'error: stage out of range 1-%s: %s\n' "$TOTAL_STAGES" "$part" >&2
      exit 1
    fi
    for ((n = lo; n <= hi; n++)); do SELECTED_LIST+=("$n"); done
  done
}

# require NAME "Stage N": exits with a clear message if $NAME (an ENV_FILE-
# backed value like GCP_PROJECT/VM_ZONE/DEPLOY_HOST, preloaded below) is
# still empty — the stage that normally sets it hasn't run yet, in this
# invocation or any prior one. Without this, a standalone stage run would
# instead fail deep inside gcloud/ssh with a cryptic empty-argument error.
require() {
  local name="$1" prereq="$2"
  if [[ -z "${!name:-}" ]]; then
    warn "Stage $_STAGE_INDEX needs \$$name, which $prereq sets — run that first."
    exit 1
  fi
}

# require_file PATH "Stage N": same as require, for a file a prior stage
# must have created (the CI SSH key) rather than an ENV_FILE value.
require_file() {
  local path="$1" prereq="$2"
  if [[ ! -f "$path" ]]; then
    warn "Stage $_STAGE_INDEX needs $path, which $prereq creates — run that first."
    exit 1
  fi
}

case "${1:-}" in
  -h|--help)
    usage
    exit 0
    ;;
  -l|--list)
    printf 'Stages:\n'
    for ((n = 1; n <= TOTAL_STAGES; n++)); do
      printf '  %2d  %s\n' "$n" "${STAGE_TITLES[n - 1]}"
    done
    exit 0
    ;;
  '')
    for ((n = 1; n <= TOTAL_STAGES; n++)); do SELECTED_LIST+=("$n"); done
    ;;
  *)
    parse_stage_spec "$1"
    ;;
esac

# Run from the repo root regardless of where the wizard is invoked.
REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
cd "$REPO_ROOT"

# All wizard state is local until it's shipped to the box: the box .env is built
# up here, then scp'd across in Stage 11. Both dirs are gitignored.
STATE_DIR="scripts/deploy/.state"
SSH_DIR="scripts/deploy/.ssh"
mkdir -p "$STATE_DIR" "$SSH_DIR"
chmod 700 "$SSH_DIR"
ENV_FILE="$STATE_DIR/box.env"          # every write_env below lands here
CI_KEY="$SSH_DIR/pictogram_deploy"     # the key CI uses to reach the box
VM_NAME="pictogram"                    # fixed, not user-provided — never in ENV_FILE
DEPLOY_USER=deploy                     # ditto; box_ssh/box_scp below hardcode it too

# A stage run standalone (via STAGE_SPEC) may skip the stage that would
# normally have computed one of these in this same invocation — fall back to
# the value a prior run already saved. A stage that DOES run overwrites it.
GCP_PROJECT="$(_existing GCP_PROJECT || true)"
VM_ZONE="$(_existing VM_ZONE || true)"
DEPLOY_HOST="$(_existing DEPLOY_HOST || true)"

# ssh/scp into the box as the `deploy` user with the CI key (no agent, no host
# prompt — the wizard has already trusted the host in Stage 5).
box_ssh()  { ssh  -i "$CI_KEY" -o StrictHostKeyChecking=accept-new "deploy@${DEPLOY_HOST}" "$@"; }
box_scp()  { scp  -i "$CI_KEY" -o StrictHostKeyChecking=accept-new "$@"; }
# Run a command on the box before the deploy user/key exist, via gcloud's own SSH
# (it manages its keys and the OS Login / metadata dance).
gvm() { gcloud compute ssh "$VM_NAME" --zone "$VM_ZONE" --command "$1"; }

# ── Stage 1 ──────────────────────────────────────────────────────────────
stage_1() {
stage 1
say "Checking the tools this wizard drives."
missing=0
for bin in gcloud gh node ssh scp openssl; do
  if command -v "$bin" >/dev/null 2>&1; then
    step "$bin ✓"
  else
    warn "$bin is not on PATH"
    missing=1
  fi
done
if [[ "$missing" == 1 ]]; then
  warn "Install the missing tools and re-run. gcloud: https://cloud.google.com/sdk/docs/install"
  exit 1
fi
if gh auth status >/dev/null 2>&1; then
  step "gh authenticated ✓"
else
  say "gh is not logged in. In another terminal run:  gh auth login  (needs the 'repo' scope)"
  pause "Press Enter once gh auth login succeeds"
fi
}

# ── Stage 2 ──────────────────────────────────────────────────────────────
stage_2() {
stage 2
say "The box lives in a GCP project you own. This uses the \$300 free-trial credit"
say "as an explicitly temporary host — migrating off GCP before it expires is #176."
open_url "https://console.cloud.google.com/projectcreate"
step "Create a project (e.g. 'pictogram') or note an existing project ID."
say "Signing in to gcloud (a browser window will open):"
gcloud auth login
ask GCP_PROJECT "Project ID:"
gcloud config set project "$GCP_PROJECT"
write_env GCP_PROJECT "$GCP_PROJECT"
}

# ── Stage 3 ──────────────────────────────────────────────────────────────
stage_3() {
stage 3
require GCP_PROJECT "Stage 2"
say "The project needs the billing account that carries the free-trial credit."
open_url "https://console.cloud.google.com/billing"
step "Copy the Billing account ID of the account holding the credit (format 0X0X0X-0X0X0X-0X0X0X)."
ask GCP_BILLING "Billing account ID:"
gcloud billing projects link "$GCP_PROJECT" --billing-account "$GCP_BILLING"
write_env GCP_BILLING "$GCP_BILLING"
say "Enabling the Compute Engine API (takes ~1 min):"
gcloud services enable compute.googleapis.com
}

# ── Stage 4 ──────────────────────────────────────────────────────────────
stage_4() {
stage 4
ask VM_REGION "Region [europe-west1]:"; VM_REGION="${VM_REGION:-europe-west1}"
ask VM_ZONE   "Zone [${VM_REGION}-b]:"; VM_ZONE="${VM_ZONE:-${VM_REGION}-b}"
write_env VM_REGION "$VM_REGION"
write_env VM_ZONE "$VM_ZONE"
say "Reserving a static external IP ('pictogram-ip'):"
gcloud compute addresses create pictogram-ip --region "$VM_REGION" 2>/dev/null \
  || note "pictogram-ip already exists — reusing it"
DEPLOY_HOST=$(gcloud compute addresses describe pictogram-ip --region "$VM_REGION" --format 'value(address)')
say "Static IP: $DEPLOY_HOST"
say "Opening 22/80/443 to the box ('pictogram-ingress'):"
gcloud compute firewall-rules create pictogram-ingress \
  --allow tcp:22,tcp:80,tcp:443 --target-tags pictogram --direction INGRESS 2>/dev/null \
  || note "pictogram-ingress already exists — reusing it"
}

# ── Stage 5 ──────────────────────────────────────────────────────────────
stage_5() {
stage 5
require VM_ZONE "Stage 4"
say "e2-medium (2 vCPU / 4 GB), Ubuntu LTS, 30 GB disk, tagged 'pictogram'."
note "~\$28/month all-in, covered by the credit for ~10 months."
if gcloud compute instances describe "$VM_NAME" --zone "$VM_ZONE" >/dev/null 2>&1; then
  note "Instance 'pictogram' already exists — skipping creation."
else
  confirm "Create the e2-medium instance now?" || { warn "Aborted."; exit 1; }
  gcloud compute instances create "$VM_NAME" \
    --zone "$VM_ZONE" \
    --machine-type e2-medium \
    --image-family ubuntu-2404-lts-amd64 --image-project ubuntu-os-cloud \
    --boot-disk-size 30GB --boot-disk-type pd-balanced \
    --address pictogram-ip \
    --tags pictogram
fi
write_env DEPLOY_HOST "$DEPLOY_HOST"
say "Waiting for SSH on the box to come up..."
until gvm "true" >/dev/null 2>&1; do printf '.'; sleep 5; done
printf '\n'; step "box reachable ✓"
}

# ── Stage 6 ──────────────────────────────────────────────────────────────
stage_6() {
stage 6
require VM_ZONE "Stage 4"
require DEPLOY_HOST "Stage 5"
say "CI reaches the box over SSH as a dedicated 'deploy' user with its own key."
if [[ -f "$CI_KEY" ]]; then
  note "Key already generated at $CI_KEY — reusing it."
else
  ssh-keygen -t ed25519 -N '' -C 'pictogram-ci-deploy' -f "$CI_KEY" >/dev/null
  step "generated $CI_KEY"
fi
CI_PUBKEY=$(cat "${CI_KEY}.pub")
say "Creating the 'deploy' user on the box and trusting the key:"
gvm "sudo useradd -m -s /bin/bash deploy 2>/dev/null || true; \
     sudo mkdir -p /home/deploy/.ssh /home/deploy/pictogram; \
     echo '$CI_PUBKEY' | sudo tee /home/deploy/.ssh/authorized_keys >/dev/null; \
     sudo chmod 700 /home/deploy/.ssh; sudo chmod 600 /home/deploy/.ssh/authorized_keys; \
     sudo chown -R deploy:deploy /home/deploy/.ssh /home/deploy/pictogram"
write_env DEPLOY_USER "$DEPLOY_USER"
box_ssh "echo connected as \$(whoami)" && step "CI key works ✓"
}

# ── Stage 7 ──────────────────────────────────────────────────────────────
stage_7() {
stage 7
require VM_ZONE "Stage 4"
require DEPLOY_HOST "Stage 5"
require_file "$CI_KEY" "Stage 6"
say "Docker Engine + the compose plugin, from Docker's official convenience script."
gvm "command -v docker >/dev/null 2>&1 && echo present || (curl -fsSL https://get.docker.com | sudo sh)"
gvm "sudo usermod -aG docker deploy"
box_ssh "docker version --format '{{.Server.Version}}'" && step "docker ready for the deploy user ✓"
}

# ── Stage 8 ──────────────────────────────────────────────────────────────
stage_8() {
stage 8
require DEPLOY_HOST "Stage 5"
require_file "$CI_KEY" "Stage 6"
say "The box pulls the app/chat/caddy images from GitHub Container Registry."
open_url "https://github.com/settings/tokens/new?scopes=read:packages&description=pictogram-box-ghcr"
step "Generate a classic token with only 'read:packages'. Copy it."
ask GHCR_USER "Your GitHub username:"
ask_secret GHCR_TOKEN "Paste the read:packages token:"
box_ssh "docker login ghcr.io -u '$GHCR_USER' --password-stdin" <<<"$GHCR_TOKEN" \
  && step "GHCR login stored on the box ✓"
note "Not written anywhere local — it lives only in the box's docker config."
}

# ── Stage 9 ──────────────────────────────────────────────────────────────
stage_9() {
stage 9
say "Signing key (ADR-0004), its public half for chat (ADR-0014), and DB / MinIO creds."
if [[ -n "$(_existing PICTOGRAM_AUTH_SIGNING_KEY || true)" ]] && ! confirm "Signing key already generated — regenerate it?"; then
  note "Keeping the existing signing key."
else
  SIGNING_KEY=$(node -e '
    const { webcrypto } = require("crypto");
    (async () => {
      const kp = await webcrypto.subtle.generateKey({ name: "ECDSA", namedCurve: "P-256" }, true, ["sign", "verify"]);
      const jwk = await webcrypto.subtle.exportKey("jwk", kp.privateKey);
      const kid = "pictogram-" + new Date().toISOString().slice(0, 10) + "-" + Math.random().toString(36).slice(2, 8);
      process.stdout.write(JSON.stringify({ kty: jwk.kty, crv: jwk.crv, kid, x: jwk.x, y: jwk.y, d: jwk.d }));
    })();
  ')
  PUBLIC_KEY=$(node -e 'const j = JSON.parse(process.argv[1]); delete j.d; process.stdout.write(JSON.stringify(j));' "$SIGNING_KEY")
  write_env PICTOGRAM_AUTH_SIGNING_KEY "$SIGNING_KEY"
  write_env PICTOGRAM_AUTH_PUBLIC_KEY "$PUBLIC_KEY"
fi
[[ -n "$(_existing POSTGRES_PASSWORD || true)" ]] || write_env POSTGRES_PASSWORD "$(openssl rand -hex 24)"
[[ -n "$(_existing MINIO_ROOT_USER || true)"   ]] || write_env MINIO_ROOT_USER "pictogram"
[[ -n "$(_existing MINIO_ROOT_PASSWORD || true)" ]] || write_env MINIO_ROOT_PASSWORD "$(openssl rand -hex 24)"
write_env PICTOGRAM_TAG "latest"
step "box.env now holds $(grep -c '=' "$ENV_FILE") values"
}

# ── Stage 10 ─────────────────────────────────────────────────────────────
stage_10() {
stage 10
say "A single free-tier org gives Alloy somewhere to push app/chat metrics and scrubbed"
say "app/chat/caddy logs. Free tier is plenty for a portfolio app's traffic."
open_url "https://grafana.com/products/cloud/"
step "Click 'Create free account' (sign in instead if you already have one)."
note "The signup flow moves around on grafana.com — if a step here doesn't match what you"
note "see, grafana.com/docs/grafana-cloud/get-started/create-account/ has the current one."
say "Signing up drops you straight into the Cloud Portal for your new org's default stack."
step "If you land elsewhere: sign in at grafana.com, then click 'My Account' to reach it."
say "In the Cloud Portal, under your stack's 'Prometheus' section:"
step "Copy the 'Remote Write Endpoint' URL and the 'Username / Instance ID'."
ask GRAFANA_CLOUD_PROMETHEUS_URL "Prometheus remote-write URL:"
ask GRAFANA_CLOUD_PROMETHEUS_USER "Prometheus username / instance ID:"
step "Click 'Generate now' for a Prometheus API key (scope: metrics:write) and copy it."
ask_secret GRAFANA_CLOUD_PROMETHEUS_API_KEY "Prometheus API key:"
say "Under 'Loki' on the same page:"
step "Copy the 'URL' (the push endpoint) and the 'Username / Instance ID'."
ask GRAFANA_CLOUD_LOKI_URL "Loki push URL:"
ask GRAFANA_CLOUD_LOKI_USER "Loki username / instance ID:"
step "Generate a Loki API key (scope: logs:write) and copy it."
ask_secret GRAFANA_CLOUD_LOKI_API_KEY "Loki API key:"
write_env GRAFANA_CLOUD_PROMETHEUS_URL "$GRAFANA_CLOUD_PROMETHEUS_URL"
write_env GRAFANA_CLOUD_PROMETHEUS_USER "$GRAFANA_CLOUD_PROMETHEUS_USER"
write_env GRAFANA_CLOUD_PROMETHEUS_API_KEY "$GRAFANA_CLOUD_PROMETHEUS_API_KEY"
write_env GRAFANA_CLOUD_LOKI_URL "$GRAFANA_CLOUD_LOKI_URL"
write_env GRAFANA_CLOUD_LOKI_USER "$GRAFANA_CLOUD_LOKI_USER"
write_env GRAFANA_CLOUD_LOKI_API_KEY "$GRAFANA_CLOUD_LOKI_API_KEY"
}

# ── Stage 11 ─────────────────────────────────────────────────────────────
stage_11() {
stage 11
require DEPLOY_HOST "Stage 5"
require_file "$CI_KEY" "Stage 6"
say "Copies compose.yaml, compose.prod.yaml, Caddyfile.prod and the Alloy config into"
say "~/pictogram, and the assembled box.env as ~/pictogram/.env."
box_ssh "mkdir -p pictogram/alloy"
box_scp compose.yaml compose.prod.yaml Caddyfile.prod "deploy@${DEPLOY_HOST}:pictogram/"
box_scp alloy/config.alloy "deploy@${DEPLOY_HOST}:pictogram/alloy/config.alloy"
box_scp "$ENV_FILE" "deploy@${DEPLOY_HOST}:pictogram/.env"
box_ssh "chmod 600 pictogram/.env && ls -l pictogram/"
step "box is staged — it will start serving once Stage $TOTAL_STAGES fills the domain + OAuth values"
}

# ── Stage 12 ─────────────────────────────────────────────────────────────
stage_12() {
stage 12
require_file "$CI_KEY" "Stage 6"
say "The Deploy workflow (.github/workflows/deploy.yml) reads these."
set_secret DEPLOY_SSH_KEY "$(cat "$CI_KEY")"
set_secret DEPLOY_USER "$DEPLOY_USER"
# DEPLOY_HOST (and its pinned host key) are set in the domain-gated tail, not here. The
# workflow rolls the box the moment DEPLOY_HOST exists — and the box cannot serve until
# the tail fills the domain + OAuth values — so setting it now would only make dispatches
# fail on the missing ${PICTOGRAM_DOMAIN} guard. Pre-domain, it builds/pushes/validates only.
note "DEPLOY_HOST is deliberately unset until Stage $TOTAL_STAGES — a dispatch now builds and pushes, no box roll."
}

# ── Stage 13 ─────────────────────────────────────────────────────────────
stage_13() {
stage 13
require DEPLOY_HOST "Stage 5"
require_file "$CI_KEY" "Stage 6"
say "Two Sentry projects — one per half of the app — feeding backend + frontend errors."
open_url "https://sentry.io/signup/"
step "Sign up (or sign in) on Sentry's free Developer plan; create an org if you don't have one."
step "Note your org's slug (the name in its URL, e.g. sentry.io/organizations/<slug>/)."
ask SENTRY_ORG "Sentry org slug:"
write_env SENTRY_ORG "$SENTRY_ORG"
set_var SENTRY_ORG "$SENTRY_ORG"
open_url "https://sentry.io/organizations/${SENTRY_ORG}/projects/"
step "Create Project → platform 'Spring Boot' (e.g. 'pictogram-backend')."
step "Copy its DSN from Settings → Projects → <project> → Client Keys (DSN)."
note "A DSN is a public identifier, safe to embed in a client bundle — not a secret."
ask SENTRY_DSN "Backend DSN:"
write_env SENTRY_DSN "$SENTRY_DSN"
step "Back on the projects page, Create Project → platform 'React' (e.g. 'pictogram-frontend')."
step "Note its project slug (the name in its URL) and copy its DSN the same way."
ask SENTRY_PROJECT "Frontend project slug:"
write_env SENTRY_PROJECT "$SENTRY_PROJECT"
set_var SENTRY_PROJECT "$SENTRY_PROJECT"
ask VITE_SENTRY_DSN "Frontend DSN:"
write_env VITE_SENTRY_DSN "$VITE_SENTRY_DSN"
set_var VITE_SENTRY_DSN "$VITE_SENTRY_DSN"
open_url "https://sentry.io/orgredirect/organizations/${SENTRY_ORG}/settings/auth-tokens/"
step "Create an org auth token scoped to 'project:releases' (source-map uploads only)."
ask_secret SENTRY_AUTH_TOKEN "Source-map upload auth token:"
set_secret SENTRY_AUTH_TOKEN "$SENTRY_AUTH_TOKEN"
box_scp "$ENV_FILE" "deploy@${DEPLOY_HOST}:pictogram/.env"
box_ssh "chmod 600 pictogram/.env"
step "box.env re-shipped with SENTRY_DSN ✓"
}

# ── Stage 14 ─────────────────────────────────────────────────────────────
stage_14() {
stage 14
require DEPLOY_HOST "Stage 5"
require_file "$CI_KEY" "Stage 6"
say "Everything above is done. The box is provisioned and CI can reach it, but it"
say "cannot serve until it has a domain (for the TLS cert) and a real Google OAuth"
say "client. Do the following when the domain is registered, then re-run this wizard"
say "(the earlier stages will no-op) or apply the steps by hand:"
printf '\n'
step "Register the domain at Cloudflare Registrar (the zone is on Cloudflare DNS already)."
step "Pictogram runs on a SUBDOMAIN (e.g. pictogram.imshy.me) so the apex stays free."
step "DNS: add  A  pictogram  ${DEPLOY_HOST}   (host 'pictogram', not '@'; AAAA too if the"
step "     VM has IPv6), and DNS-only — NOT proxied (the orange cloud breaks ACME + rate limits)."
open_url "https://console.cloud.google.com/apis/credentials"
step "Create an OAuth 2.0 Client ID, type 'Web application'."
step "Authorized redirect URI:  https://<domain>/login/oauth2/code/google"
step "Configure the OAuth consent screen (app name, support email, scopes openid + email)."
printf '\n'
if confirm "Have the domain and OAuth client details now?"; then
  ask PICTOGRAM_DOMAIN "Full subdomain (e.g. pictogram.imshy.me):"
  ask GOOGLE_CLIENT_ID "Google client ID:"
  ask_secret GOOGLE_CLIENT_SECRET "Google client secret:"
  write_env PICTOGRAM_DOMAIN "$PICTOGRAM_DOMAIN"
  write_env GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
  write_env GOOGLE_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET"
  box_scp "$ENV_FILE" "deploy@${DEPLOY_HOST}:pictogram/.env"
  box_ssh "chmod 600 pictogram/.env"
  set_secret DEPLOY_HOST "$PICTOGRAM_DOMAIN"
  # Re-key the pinned host entry for the domain name (same box key, connected-as name).
  set_secret DEPLOY_KNOWN_HOSTS "$(ssh-keyscan "$DEPLOY_HOST" 2>/dev/null | sed "s/^[^ ]*/$PICTOGRAM_DOMAIN/")"
  say "Now trigger the Deploy workflow:  Actions → Deploy → Run workflow"
  say "Then work through the smoke test in docs/runbook/deployment.md."
else
  note "No problem — re-run the wizard when you're ready; Stages 1–$((TOTAL_STAGES - 1)) will skip."
fi
}

# ── Run the selected stages, in order ─────────────────────────────────────
if (( ${#SELECTED_LIST[@]} == TOTAL_STAGES )); then
  BANNER_NOTE=""
else
  joined="${SELECTED_LIST[*]}"
  BANNER_NOTE="Running only stage(s): ${joined// /, }"
fi
banner "Pictogram deployment (ADR-0012)" "$BANNER_NOTE"
say "Provisions the temporary GCP box, wires CI to it, and prepares the box .env."
note "Pre-domain stages run now; the domain-gated tail (Stage $TOTAL_STAGES) waits until you own the domain."

for ((n = 1; n <= TOTAL_STAGES; n++)); do
  if is_selected "$n"; then
    "stage_$n"
  fi
done

finish
